# Question 3: Model Evaluation and Comparison 


## Which model should be chosen for medical diagnosis and why?

**Answer:**

For medical diagnosis, **Model A should be chosen**.

### Reason

In medical applications, the most important metric is **Recall** (also called **Sensitivity**).

Recall measures how many actual positive cases (patients who truly have the disease) are correctly identified by the model.

**Formula:**
Recall = TP / (TP + FN)


Where:
- **TP** = True Positives (correctly detected disease cases)
- **FN** = False Negatives (missed disease cases)

### Why Recall is Important in Medical Diagnosis

A **False Negative** means the model predicts that a patient is healthy when they actually have the disease. This is very dangerous because the patient may not receive necessary treatment.

Therefore, in healthcare systems we prioritize **higher Recall to minimize False Negatives**.

### Model Comparison

| Metric | Model A | Model B |
|------|------|------|
| Accuracy | 0.85 | 0.82 |
| Precision | 0.91 | 0.94 |
| Recall | **0.83** | 0.75 |
| F1 Score | **0.87** | 0.83 |

### Conclusion

Although **Model B has slightly higher precision**, **Model A has higher recall**, meaning it correctly identifies more disease cases.

Therefore, **Model A is preferred for medical diagnosis because it reduces the risk of missing patients who actually have the disease**.

In [2]:
import pandas as pd
import numpy as np

In [ ]:
    
def cal(con_1):
    accuracy_1 = round((con_1[0, 0] + con_1[1, 1]) / np.sum(con_1), 2)

    recall_1 = round(con_1[0, 0] / (con_1[0, 0] + con_1[0, 1]), 2)

    precision_1 = round(con_1[0, 0] / (con_1[0, 0] + con_1[1, 0]), 2)

    f1_score_1 = round((2 * (precision_1 * recall_1) / (precision_1 + recall_1)), 2)

    print("Confusion Matrix :")
    print(con_1)
    print("Accuracy :", accuracy_1)
    print("Precision :", precision_1)
    print("Recall :", recall_1)
    print("F1 Score :", f1_score_1)




In [6]:

con_1 = np.array([[50, 10], [5, 35]])
con_2 = np.array([[45, 15], [3, 37]])

cal(con_1)
cal(con_2)

Confusion Matrix 1:
[[50 10]
 [ 5 35]]
Accuracy 1: 0.85
Precision 1: 0.91
Recall 1: 0.83
F1 Score 1: 0.87
Confusion Matrix 1:
[[45 15]
 [ 3 37]]
Accuracy 1: 0.82
Precision 1: 0.94
Recall 1: 0.75
F1 Score 1: 0.83


In [5]:
cal(np.array([[80, 20], [10, 90]]))


Confusion Matrix 1:
[[80 20]
 [10 90]]
Accuracy 1: 0.85
Precision 1: 0.89
Recall 1: 0.8
F1 Score 1: 0.84
