## numpy

In [4]:
import numpy as np

#### Question 1: Create and Inspect an ndarray

In [5]:

arr = np.array([10, 20, 30, 40, 50, 60])
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)


Array: [10 20 30 40 50 60]
Shape: (6,)
Data Type: int64
Dimensions: 1


#### Question 2: Indexing and Slicing

In [6]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])
print("Element at row2 col3:",arr[1,2])
print("Second row:",arr[1])
print("First row:",arr[0])
print("Last column:",arr[:,-1])

Element at row2 col3: 30
Second row: [20 25 30]
First row: [ 5 10 15]
Last column: [15 30 45]


#### Question 3: Reshaping an Array

In [7]:
arr = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,12])
arr = arr.reshape(3,4)
print("Reshaped (3x4):")
print(arr)
print("")
arr = arr.reshape(4,3)
print("Reshaped (4x3):")
print(arr)


Reshaped (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Question 4: Broadcasting

In [8]:
A = np.array([1,2,3])
B = np.array([[10],
              [20],
              [30]])
print("Result:")
print(A+B)

Result:
[[11 12 13]
 [21 22 23]
 [31 32 33]]


#### Question 5: Aggregation Functions

In [9]:
arr = np.array([4,7,2,9,5,1])

print("sum:", np.sum(arr))
print("mean:", round(np.mean(arr), 2))
print("max:", np.max(arr))
print("min:", np.min(arr))
print("standard deviation:", np.std(arr))

sum: 28
mean: 4.67
max: 9
min: 1
standard deviation: 2.748737083745107


#### Question 6: Random Module

In [10]:
from numpy import random

In [42]:
arr = np.random.randint(10,51 , size = 5)
print("Random Array:")
print(arr)
print("")
arr = np.random.rand(3,3) #range [0,1)


print("Random matrix:"  )
print(arr)

Random Array:
[43 48 23 33 13]

Random matrix:
[[0.36496357 0.24932482 0.20501131]
 [0.54945961 0.01945505 0.55033947]
 [0.07574476 0.39574313 0.89123566]]


#### Question 7: Linear Algebra (Dot Product)

In [43]:
A = np.array([2,4,6])
B = np.array([1,3,5])

print("Dot Product:", np.dot(A,B))

Dot Product: 44


## Pandas

In [45]:
import pandas as pd

#### Question 8: Create Series

In [54]:
arr  = pd.DataFrame([25,30,35,40,45])

print("series:" , arr)

print("mean: " , round(arr.mean()[0]))

print("max: " , arr.max()[0])

series:     0
0  25
1  30
2  35
3  40
4  45
mean:  35
max:  45


#### Question 9: DataFrame Creation

In [58]:
data_set = {
    "Name" :["Ravi" , "Meena" , "Jhon"] ,
    "Age" : [25, 30, 28] ,
    "Salary" : [50000, 60000, 55000]
}

df = pd.DataFrame(data_set)
df_New = df[df["Age"]>26]
print(df_New)

    Name  Age  Salary
1  Meena   30   60000
2   Jhon   28   55000


#### Question 10: loc and iloc

In [ ]:
data_set = pd.DataFrame({
    "Name" :["Ravi" , "Meena" , "Jhon"] ,
    "Age" : [25, 30, 28] ,
    "Salary" : [50000, 60000, 55000]
}  , index = ["Emp1" , "Emp2" , "Emp3"])


print("using loc:")
print(data_set.loc["Emp2"])
print("\nusing iloc:")
print(data_set.iloc[0])

using loc:
Name      Meena
Age          30
Salary    60000
Name: Emp2, dtype: object

using iloc:
Name       Ravi
Age          25
Salary    50000
Name: Emp1, dtype: object


#### Question 11: Sorting Data

In [78]:
print(data_set.sort_values(by = "Salary" , ascending = False))


       Name  Age  Salary
Emp2  Meena   30   60000
Emp3   Jhon   28   55000
Emp1   Ravi   25   50000


#### Question 12: GroupBy Operation

In [86]:
df = pd.read_excel("12.xlsx")


In [85]:
group_data = df.groupby("Department")["Salary"].mean()
print(group_data)

Department
HR    56000.0
IT    52500.0
Name: Salary, dtype: float64


#### Question 13: Merge DataFrames

In [93]:
df1 = pd.DataFrame(
    {
        "EmpID" : [1, 2, 3]  ,
        "Name" : ["Ravi" , "Meena" , "Jhon"] ,

    }
)

df2 = pd.DataFrame(
    {   
        "EmpID" : [1, 2, 3]  ,
        "Salary" : [50000, 60000, 55000]
    }
)
merged_df = pd.merge(df1, df2, on="EmpID")
print(merged_df)

   EmpID   Name  Salary
0      1   Ravi   50000
1      2  Meena   60000
2      3   Jhon   55000


#### Question 14: Apply Function

In [ ]:
new_df = merged_df.drop("EmpID", axis=1)

In [112]:
new_df["New Salary"] = round(new_df["Salary"] * 1.1,0)
print(new_df)

    Name  Salary  New Salary
0   Ravi   50000     55000.0
1  Meena   60000     66000.0
2   Jhon   55000     60500.0
